version: "3"
services:
  db:
    image: mongo:4.2.8
    container_name: db

    ports:
      - "4000:27017" # 외부 포트:컨테이너 포트
    restart: always

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage # microservice를 제작할 폴더 지정
      dockerfile: Dockerfile
    container_name: video-storage # 생성될 때 생기는 이름
    ports:
      - "4001:80" # 외부 포트:컨테이너 포트
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=<your account name>
      - STORAGE_ACCESS_KEY=<your access key>

  minivideo-dev:
    image: minivideo-dev
    build:
      context: ./minivideo # microservice를 제작할 폴더 지정
      dockerfile: Dockerfile-dev
    container_name: minivideo-dev-container # 생성될 때 생기는 이름
    volumes:
      - /tmp/minivideo/npm-cache:/root/:z
      - ./minivideo/src:/usr/src/app:z
    ports:
      - "4002:80" # 외부 포트:컨테이너 포트
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=minivideo
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no" # 개발에서는 재시작하지 않게 설정하여 오류가 있는 부분을 확인할수 있도록 한다.
