version: "3"
services:
  db:
    image: mongo:4.2.8
    container_name: db

    ports:
      - "4000:27017" # 외부 포트:컨테이너 포트
    restart: always

  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always

  minivideo-dev:
    image: minivideo-dev
    build:
      context: ./minivideo # microservice를 제작할 폴더 지정
      dockerfile: Dockerfile-dev
    container_name: minivideo-dev-container # 생성될 때 생기는 이름
    volumes:
      - /tmp/minivideo/npm-cache:/root/:z
      - ./minivideo/src:/usr/src/app:z
      - ./minivideo/videos:/usr/src/app/videos:z
    ports:
      - "4001:80" # 외부 포트:컨테이너 포트
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
    depends_on:
      - rabbit
    restart: "no" # 개발에서는 재시작하지 않게 설정하여 오류가 있는 부분을 확인할수 있도록 한다.

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"
